substitutions:
  device_name: esphome_device
  friendly_name: ESPHomeTemplatedDevice
  min_version: 2025.11.0

  # Common display rotation 
  rotation: 90

  #CYD common pin labels
  i2c_sda: "27"
  i2c_scl: "22"

  tft_clk: "14"
  tft_mosi: "13"
  tft_miso: "12"
  tft_cs: "15"
  tft_dc: "2"

  touch_clk: "25"
  touch_mosi: "32"
  touch_miso: "39"
  touch_cs: "33"
  touch_interupt: "36"

  #Common speaker pin labels
  #speaker_i2s_lrclk_pin: "26"
  #speaker_i2s_bclk_pin: "27"
  #speaker_i2s_dout_pin: "25"
  
  #Common mic pin labels
  #mic_i2s_ws_pin: "14"
  #mic_i2s_sck_pin: "13"

  packages:
    esphome_templates:
      url: https://github.com/TemuWolverine/esphome_templates
      ref: main
      files:
        - esphome-boilerplate.yaml

        # Select a board
        #- boards/cyd.yaml
        #- boards/crowpanel_2_9_inch.yaml
        #- boards/reterminal.yaml
        #- boards/JC4880P443.yaml
#
        # Select any devices
        #- devices/i2s/INMP441.yaml
        #- devices/i2s/MAX98357.yaml