# Elecrow 2.9" Crowpanel display.
# Features an ESP32-S3-WROOM-1-N8R8, up to 240 MHz, and a 2.9" e-paper display with 128x296 resolution.
# https://www.elecrow.com/crowpanel-esp32-2-9-e-paper-hmi-display-with-128-296-resolution-black-white-color-driven-by-spi-interface.html
esphome:
  on_boot:  #needed to turn on the screen power at boot
    - priority: 600
      then: 
      - output.turn_on: screen_power

#CONFIG START
substitutions:
  screenPowerPin:   GPIO7

# These are the pins used for the SPI connected display
  mosi_pin: 11
  clk_pin: 12
  sda: 20 
  scl: 21
  cs_pin: 45
  dc_pin: 46
  reset_pin: 47
  busy_pin: 48

output:
- platform: gpio
  pin: ${screenPowerPin}
  id: screen_power

# ESP32-S3-WROOM-1-N8R8, up to 240 MHz
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Display pins
spi:
  mosi_pin: ${mosi_pin}
  clk_pin: ${clk_pin}

color:
  - id: paperwhite # Really black, but will appear white on e-paper
    hex: "000000"
  - id: paperblack # Really white, but will appear black on e-paper
    hex: FFFFFF

display:
 - platform: waveshare_epaper
   model: gdey029t94
   id: epaper_display
   cs_pin: ${cs_pin}
   dc_pin: ${dc_pin}
   reset_pin: ${reset_pin}
   busy_pin: ${busy_pin}
   update_interval: 5min
   reset_duration: 200ms
   rotation: ${rotation}