# Seeed Studio reTerminal E1001, black and white, 7.5" e-paper display, 
# ESP32-S3-WROOM-1-N8R8, up to 240 MHz.
# https://www.seeedstudio.com/reTerminal-E1001-p-6534.html
esphome:
  on_boot:
    priority: 600
    then:
      - output.turn_on: bsp_battery_enable
      - delay: 500ms   

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    
spi:
  clk_pin: GPIO7
  mosi_pin: GPIO9

display:
  - platform: waveshare_epaper
    id: epaper_display
    model: 7.50inv2
    cs_pin: GPIO10
    dc_pin: GPIO11
    reset_pin:
      number: GPIO12
      inverted: false
    busy_pin:
      number: GPIO13
      inverted: true
    rotation: 90
    update_interval: never
    
sensor:
  - platform: adc
    pin: GPIO1
    name: "Battery Voltage"
    id: battery_voltage
    update_interval: 600s
    attenuation: 12db
    filters:
      - multiply: 2.0

#    Example code from seedstudio.
  - platform: template
    name: "Battery Level"
    id: battery_level
    unit_of_measurement: "%"
    icon: "mdi:battery"
    device_class: battery
    state_class: measurement
    #lambda: 'return id(battery_voltage).state;'
    update_interval: 600s
    filters:
      - calibrate_linear:
          - 4.15 -> 100.0
          - 3.96 -> 90.0
          - 3.91 -> 80.0
          - 3.85 -> 70.0
          - 3.80 -> 60.0
          - 3.75 -> 50.0
          - 3.68 -> 40.0
          - 3.58 -> 30.0
          - 3.49 -> 20.0
          - 3.41 -> 10.0
          - 3.30 -> 5.0
          - 3.27 -> 0.0
      - clamp:
          min_value: 0
          max_value: 100

# Refresh button
binary_sensor:
  - platform: gpio
    id: btnRefresh
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
