sensor:
  - platform: dht
    model: DHT22
    pin: ${dht_pin}
    temperature:
      name: "Temperature"
      id: dht_temperature
      accuracy_decimals: 3

      # If you don't smooth the temperature readings 
      # the PID controller over reacts to small changes.
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1

    humidity:
      name: "Humidity"
      id: dht_humidity
                                                                                                                                                                                                          
    update_interval: 5s

